// Pattern family definitions and registry
// All pattern families are fixed and not user-extensible

export const PATTERN_FAMILIES = {
  // Common UI Patterns
  ONB_HERO_TOP: 'ONB_HERO_TOP',
  FEAT_IMAGE_TEXT_RIGHT: 'FEAT_IMAGE_TEXT_RIGHT',
  DEMO_DEVICE_FULLBLEED: 'DEMO_DEVICE_FULLBLEED',
  ACT_FORM_MINIMAL: 'ACT_FORM_MINIMAL',
  CTA_SPLIT_SCREEN: 'CTA_SPLIT_SCREEN',
  HERO_CENTER_TEXT: 'HERO_CENTER_TEXT',
  FEAT_IMAGE_TEXT_LEFT: 'FEAT_IMAGE_TEXT_LEFT',
  FEAT_IMAGE_TEXT_CENTER: 'FEAT_IMAGE_TEXT_CENTER',
  TESTIMONIAL_CARD_GRID: 'TESTIMONIAL_CARD_GRID',
  PRICING_TABLE: 'PRICING_TABLE',
  ABOUT_TEAM_GRID: 'ABOUT_TEAM_GRID',
  BLOG_HERO_CENTER: 'BLOG_HERO_CENTER',
  PRODUCT_SHOWCASE: 'PRODUCT_SHOWCASE',
  FOOTER_MULTI_COLUMN: 'FOOTER_MULTI_COLUMN',
  NAV_HEADER_STICKY: 'NAV_HEADER_STICKY',
  STATS_COUNTER_ROW: 'STATS_COUNTER_ROW',
  LOGO_CLOUD_BANNER: 'LOGO_CLOUD_BANNER',
  FAQ_ACCORDION: 'FAQ_ACCORDION',
  GALLERY_GRID: 'GALLERY_GRID',
  TIMELINE_VERTICAL: 'TIMELINE_VERTICAL',
  COMPARISON_TABLE: 'COMPARISON_TABLE',
  NEWSLETTER_SIGNUP: 'NEWSLETTER_SIGNUP',
  CONTACT_FORM: 'CONTACT_FORM',
  MAP_EMBED: 'MAP_EMBED',

  // E-commerce Domain
  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
  CART_SUMMARY: 'CART_SUMMARY',
  CHECKOUT_STEPS: 'CHECKOUT_STEPS',
  ORDER_CONFIRMATION: 'ORDER_CONFIRMATION',
  PRODUCT_GRID: 'PRODUCT_GRID',
  CATEGORY_FILTER: 'CATEGORY_FILTER',

  // SaaS Domain
  DASHBOARD_OVERVIEW: 'DASHBOARD_OVERVIEW',
  DASHBOARD_SIDEBAR: 'DASHBOARD_SIDEBAR',
  ONB_STEP_WIZARD: 'ONB_STEP_WIZARD',
  FEAT_COMPARISON: 'FEAT_COMPARISON',
  PRICING_TIERED: 'PRICING_TIERED',
  INTEGRATION_LIST: 'INTEGRATION_LIST',

  // Mobile App Domain
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  ONB_SWIPE_CARDS: 'ONB_SWIPE_CARDS',
  SETTINGS_LIST: 'SETTINGS_LIST',
  PROFILE_HEADER: 'PROFILE_HEADER',
} as const

export type PatternFamily = typeof PATTERN_FAMILIES[keyof typeof PATTERN_FAMILIES]

// Array of all pattern families for iteration
export const ALL_PATTERN_FAMILIES = Object.values(PATTERN_FAMILIES)

// Pattern family domains
export const PATTERN_DOMAINS = {
  COMMON: 'common',
  ECOMMERCE: 'ecommerce',
  SAAS: 'saas',
  MOBILE: 'mobile',
} as const

export type PatternDomain = typeof PATTERN_DOMAINS[keyof typeof PATTERN_DOMAINS]

